# model:
#   name: google/bert_uncased_L-2_H-128_A-2
#   tokenizer: google/bert_uncased_L-2_H-128_A-2

# processing:
#   batch_size: 64
#   max_length: 128

# training:
#   max_epochs: 1
#   log_every_n_steps: 10
#   deterministic: true
#   limit_train_batches: 0.25
#   limit_val_batches: 0.25

# shifiting them to separate folders for scalability of project

defaults:
  - model: default                            # model config is in model folder : lookfor default yaml file
  - processing: default                       # processing related config is in model folder : lookfor default yaml file
  - training: default                         # training related config is in model folder : look for default yaml file
  - override hydra/job_logging: colorlog      # for better user experience logging
  - override hydra/hydra_logging: colorlog