name: Create Docker Container

on: [push]

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: iterative/setup-dvc@v1
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - run: |
          dvc remote add -d storage gdrive://1dHJbiw5fzNs7cVDby0e5jVyPhv4pgcCg
          dvc remote modify storage gdrive_use_service_account true
      - name: list files in the repository
      - run: |
          ls ${{github.workspace}}
        
      - name: Build container
        run: |
          docker network create data
          docker build --tag predict:latest .
          docker run -d -p 8000:8000 --network data --name prediction_container predict:latest
