name: Create Docker Container

on: [push]

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: iterative/setup-dvc@v1
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - run: |
          echo -E '${{ secrets.GDRIVE_CREDENTIALS_DATA }}' > creds.json

          dvc remote add -d -f myremote gdrive://1dHJbiw5fzNs7cVDby0e5jVyPhv4pgcCg
          dvc remote modify myremote gdrive_use_service_account true
          dvc remote modify myremote --local gdrive_service_account_json_file_path creds.json

          dvc pull trained_model.dvc

          # Either do this or add the file to your .gitignore
          # Just make sure not to push it to your repository
          rm creds.json
          
      - name: list files in the repository
        run: |
          ls ${{github.workspace}}
        
      - name: Build container
        run: |
          docker network create data
          docker build --tag predict:latest .
          docker run -d -p 8000:8000 --network data --name prediction_container predict:latest
